"""
This program gives a toolbox for census
We have to guess the random num generated by the program.
will get only 4 chances to guess. if the 4th guess is near to the pw by
2 numbers then user will get a 5th chance.
"""
import random

def generate_random_num():
    """
    this fn generates the random num
    """
    random_num=random.randint(1,25)
    return random_num

def get_inp_num():
    """
    this fn is to get the user input
    """
    input_num=int(input('Enter the guess:'))
    return input_num

def main():
    """
    main fn to check if the guess is same as the random num
    and gives the hint accordingly
    """
    random_number=generate_random_num()
    count=1
    while(count<6) :
        guess=get_inp_num()
        if(guess==random_number):
            print('Welcome!!!')
            break
        elif(guess>random_number+2):
            if count==4 or count==5:
                print('Login Failed!!!')
                break
            print('INVALID PASSCODE')
        elif(guess<random_number-2):
            if count==4 or count==5:
                print('Login Failed!!!')
                break
            print('invalid passcode')
        else:
            if count==5:
                print('Login Failed!!!')
                break
            print('InVaLiD PaSsCoDe')
        count+=1
        
#main program starts from here
main()
